### ISSUE TITLE
SockJS 0.2.1

### ISSUE THREAD

**Issue by sophietk** [myguidingstar-zz/bower-sockjs#1]
Hi,

I was looking for a sockjs bower package and found yours. But I'm using sockjs 0.2.1. Is it possible to create a new branch to merge my future pull request into it: sophietk/bower-sockjs@88fd9550e685d257c89f6ae1e52dba2b0807185c, and then tag a 0.2.1 release ?

Thanks in advance

**Comment by myguidingstar-zz** [comment]
Thank you for doing it the open source way. However I've been converted to Clojure/Clojurescript ;) and this repository is unmaintained. Or this mess has never been maintained, as even no README is included.
I think neither you nor I should own the bower distribution the way I did. It's about security concerns because the inclueded javascript files aren't checked in terms of integrity (What if I put some dangerous lines of code in it?) Please help reaching the sockjs team and request an official repo for bower. distribution. I will unregister mine and register again the name 'sockjs' in Bower pointing to that official repo.
Cheers (<-- eh um, too soon ^^)

**Comment by sophietk** [comment]
You're right, it's obviously the best way to get an official and maintained bower package. I'm working on that. My warm thanks for your reply!
